
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Dec 15 10:00:14 CET 2013
//----------------------------------------------------

package pac3;

import java_cup.*;
import java_cup.runtime.*;
import pac3.*;
import pac3.utils.*;
import java.io.*;
import java.util.*;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Sun Dec 15 10:00:14 CET 2013
  */
public class Pac3Cup extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public Pac3Cup() {super();}

  /** Constructor which sets the default scanner. */
  public Pac3Cup(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Pac3Cup(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\077\000\002\002\004\000\002\002\004\000\002\002" +
    "\002\000\002\003\010\000\002\003\003\000\002\003\004" +
    "\000\002\003\005\000\002\004\004\000\002\004\002\000" +
    "\002\005\003\000\002\005\003\000\002\005\003\000\002" +
    "\005\003\000\002\005\003\000\002\005\003\000\002\005" +
    "\003\000\002\005\003\000\002\005\003\000\002\006\004" +
    "\000\002\006\002\000\002\007\012\000\002\007\004\000" +
    "\002\007\005\000\002\007\006\000\002\010\004\000\002" +
    "\010\002\000\002\011\004\000\002\011\004\000\002\011" +
    "\004\000\002\011\003\000\002\011\003\000\002\012\004" +
    "\000\002\012\004\000\002\012\002\000\002\013\003\000" +
    "\002\013\003\000\002\013\003\000\002\013\003\000\002" +
    "\013\003\000\002\013\003\000\002\013\003\000\002\014" +
    "\007\000\002\014\007\000\002\014\007\000\002\014\007" +
    "\000\002\014\012\000\002\014\012\000\002\014\012\000" +
    "\002\014\012\000\002\014\014\000\002\014\014\000\002" +
    "\014\014\000\002\014\014\000\002\017\004\000\002\017" +
    "\003\000\002\017\002\000\002\015\004\000\002\015\002" +
    "\000\002\016\004\000\002\016\004\000\002\016\003\000" +
    "\002\016\004\000\002\016\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\172\000\010\002\uffff\003\005\004\007\001\002\000" +
    "\010\002\uffff\003\005\004\007\001\002\000\010\002\ufffd" +
    "\003\ufffd\004\ufffd\001\002\000\004\002\173\001\002\000" +
    "\006\003\010\007\011\001\002\000\010\002\ufffc\003\ufffc" +
    "\004\ufffc\001\002\000\006\003\012\005\013\001\002\000" +
    "\010\002\ufffb\003\ufffb\004\ufffb\001\002\000\030\003\023" +
    "\006\ufff9\007\016\013\026\014\021\015\022\016\024\017" +
    "\ufff9\020\015\022\025\025\020\001\002\000\006\006\uffee" +
    "\017\031\001\002\000\030\003\ufff6\006\ufff6\007\ufff6\013" +
    "\ufff6\014\ufff6\015\ufff6\016\ufff6\017\ufff6\020\ufff6\022\ufff6" +
    "\025\ufff6\001\002\000\030\003\ufff3\006\ufff3\007\ufff3\013" +
    "\ufff3\014\ufff3\015\ufff3\016\ufff3\017\ufff3\020\ufff3\022\ufff3" +
    "\025\ufff3\001\002\000\030\003\023\006\ufff9\007\016\013" +
    "\026\014\021\015\022\016\024\017\ufff9\020\015\022\025" +
    "\025\020\001\002\000\030\003\ufff2\006\ufff2\007\ufff2\013" +
    "\ufff2\014\ufff2\015\ufff2\016\ufff2\017\ufff2\020\ufff2\022\ufff2" +
    "\025\ufff2\001\002\000\030\003\ufff8\006\ufff8\007\ufff8\013" +
    "\ufff8\014\ufff8\015\ufff8\016\ufff8\017\ufff8\020\ufff8\022\ufff8" +
    "\025\ufff8\001\002\000\030\003\ufff7\006\ufff7\007\ufff7\013" +
    "\ufff7\014\ufff7\015\ufff7\016\ufff7\017\ufff7\020\ufff7\022\ufff7" +
    "\025\ufff7\001\002\000\030\003\ufff0\006\ufff0\007\ufff0\013" +
    "\ufff0\014\ufff0\015\ufff0\016\ufff0\017\ufff0\020\ufff0\022\ufff0" +
    "\025\ufff0\001\002\000\030\003\ufff4\006\ufff4\007\ufff4\013" +
    "\ufff4\014\ufff4\015\ufff4\016\ufff4\017\ufff4\020\ufff4\022\ufff4" +
    "\025\ufff4\001\002\000\030\003\ufff1\006\ufff1\007\ufff1\013" +
    "\ufff1\014\ufff1\015\ufff1\016\ufff1\017\ufff1\020\ufff1\022\ufff1" +
    "\025\ufff1\001\002\000\030\003\ufff5\006\ufff5\007\ufff5\013" +
    "\ufff5\014\ufff5\015\ufff5\016\ufff5\017\ufff5\020\ufff5\022\ufff5" +
    "\025\ufff5\001\002\000\006\006\ufffa\017\ufffa\001\002\000" +
    "\006\006\uffee\017\031\001\002\000\006\003\034\007\035" +
    "\001\002\000\004\006\033\001\002\000\010\002\ufffe\003" +
    "\ufffe\004\ufffe\001\002\000\006\006\uffec\017\uffec\001\002" +
    "\000\006\003\036\023\037\001\002\000\006\006\uffeb\017" +
    "\uffeb\001\002\000\016\003\042\013\041\016\044\020\040" +
    "\024\uffe8\025\046\001\002\000\004\007\171\001\002\000" +
    "\004\007\170\001\002\000\022\003\uffe3\006\uffea\013\uffe3" +
    "\016\uffe3\017\uffea\020\uffe3\024\uffe3\025\uffe3\001\002\000" +
    "\004\024\052\001\002\000\004\007\051\001\002\000\016" +
    "\003\047\013\041\016\044\020\040\024\uffe8\025\046\001" +
    "\002\000\016\003\uffe4\013\uffe4\016\uffe4\020\uffe4\024\uffe4" +
    "\025\uffe4\001\002\000\016\003\uffe3\013\uffe3\016\uffe3\020" +
    "\uffe3\024\uffe3\025\uffe3\001\002\000\004\024\uffe9\001\002" +
    "\000\016\003\uffe6\013\uffe6\016\uffe6\020\uffe6\024\uffe6\025" +
    "\uffe6\001\002\000\004\005\053\001\002\000\024\003\061" +
    "\006\uffe0\007\055\013\066\016\062\020\054\022\064\025" +
    "\057\027\056\001\002\000\024\003\uffdd\006\uffdd\007\uffdd" +
    "\013\uffdd\016\uffdd\020\uffdd\022\uffdd\025\uffdd\027\uffdd\001" +
    "\002\000\026\003\uffdc\006\uffdc\007\uffdc\013\uffdc\016\uffdc" +
    "\020\uffdc\021\116\022\uffdc\025\uffdc\027\uffdc\001\002\000" +
    "\004\023\072\001\002\000\024\003\uffdb\006\uffdb\007\uffdb" +
    "\013\uffdb\016\uffdb\020\uffdb\022\uffdb\025\uffdb\027\uffdb\001" +
    "\002\000\024\003\061\006\uffe0\007\055\013\066\016\062" +
    "\020\054\022\064\025\057\027\056\001\002\000\024\003" +
    "\uffd9\006\uffd9\007\uffd9\013\uffd9\016\uffd9\020\uffd9\022\uffd9" +
    "\025\uffd9\027\uffd9\001\002\000\024\003\uffde\006\uffde\007" +
    "\uffde\013\uffde\016\uffde\020\uffde\022\uffde\025\uffde\027\uffde" +
    "\001\002\000\004\006\070\001\002\000\024\003\uffda\006" +
    "\uffda\007\uffda\013\uffda\016\uffda\020\uffda\022\uffda\025\uffda" +
    "\027\uffda\001\002\000\024\003\061\006\uffe0\007\055\013" +
    "\066\016\062\020\054\022\064\025\057\027\056\001\002" +
    "\000\024\003\uffdf\006\uffdf\007\uffdf\013\uffdf\016\uffdf\020" +
    "\uffdf\022\uffdf\025\uffdf\027\uffdf\001\002\000\004\006\uffe2" +
    "\001\002\000\006\006\uffed\017\uffed\001\002\000\004\006" +
    "\uffe1\001\002\000\012\007\076\010\073\011\075\012\074" +
    "\001\002\000\012\003\077\011\102\024\uffc8\026\103\001" +
    "\002\000\012\003\077\011\102\024\uffc8\026\103\001\002" +
    "\000\012\003\077\011\102\024\uffc8\026\103\001\002\000" +
    "\012\003\077\011\102\024\uffc8\026\103\001\002\000\014" +
    "\003\uffc3\011\uffc3\022\uffc3\024\uffc3\026\uffc3\001\002\000" +
    "\004\024\110\001\002\000\014\003\077\011\102\022\uffc8" +
    "\024\uffc8\026\103\001\002\000\014\003\uffc5\011\uffc5\022" +
    "\uffc5\024\uffc5\026\uffc5\001\002\000\010\007\106\010\104" +
    "\012\105\001\002\000\014\003\uffc6\011\uffc6\022\uffc6\024" +
    "\uffc6\026\uffc6\001\002\000\014\003\uffc4\011\uffc4\022\uffc4" +
    "\024\uffc4\026\uffc4\001\002\000\014\003\uffc7\011\uffc7\022" +
    "\uffc7\024\uffc7\026\uffc7\001\002\000\006\022\uffc9\024\uffc9" +
    "\001\002\000\004\032\111\001\002\000\014\003\113\007" +
    "\115\027\056\030\uffca\031\uffca\001\002\000\014\003\113" +
    "\007\115\027\056\030\uffca\031\uffca\001\002\000\006\030" +
    "\uffcb\031\uffcb\001\002\000\006\030\134\031\133\001\002" +
    "\000\004\021\116\001\002\000\012\007\122\010\117\011" +
    "\121\012\120\001\002\000\012\003\077\011\102\022\uffc8" +
    "\026\103\001\002\000\012\003\077\011\102\022\uffc8\026" +
    "\103\001\002\000\012\003\077\011\102\022\uffc8\026\103" +
    "\001\002\000\012\003\077\011\102\022\uffc8\026\103\001" +
    "\002\000\004\022\124\001\002\000\030\003\uffd8\006\uffd8" +
    "\007\uffd8\013\uffd8\016\uffd8\020\uffd8\022\uffd8\025\uffd8\027" +
    "\uffd8\030\uffd8\031\uffd8\001\002\000\004\022\126\001\002" +
    "\000\030\003\uffd6\006\uffd6\007\uffd6\013\uffd6\016\uffd6\020" +
    "\uffd6\022\uffd6\025\uffd6\027\uffd6\030\uffd6\031\uffd6\001\002" +
    "\000\004\022\130\001\002\000\030\003\uffd5\006\uffd5\007" +
    "\uffd5\013\uffd5\016\uffd5\020\uffd5\022\uffd5\025\uffd5\027\uffd5" +
    "\030\uffd5\031\uffd5\001\002\000\004\022\132\001\002\000" +
    "\030\003\uffd7\006\uffd7\007\uffd7\013\uffd7\016\uffd7\020\uffd7" +
    "\022\uffd7\025\uffd7\027\uffd7\030\uffd7\031\uffd7\001\002\000" +
    "\030\003\uffd4\006\uffd4\007\uffd4\013\uffd4\016\uffd4\020\uffd4" +
    "\022\uffd4\025\uffd4\027\uffd4\030\uffd4\031\uffd4\001\002\000" +
    "\012\003\113\007\115\027\056\031\uffca\001\002\000\004" +
    "\031\136\001\002\000\030\003\uffd0\006\uffd0\007\uffd0\013" +
    "\uffd0\016\uffd0\020\uffd0\022\uffd0\025\uffd0\027\uffd0\030\uffd0" +
    "\031\uffd0\001\002\000\006\030\uffcc\031\uffcc\001\002\000" +
    "\004\024\141\001\002\000\004\032\142\001\002\000\014" +
    "\003\113\007\115\027\056\030\uffca\031\uffca\001\002\000" +
    "\006\030\145\031\144\001\002\000\030\003\uffd2\006\uffd2" +
    "\007\uffd2\013\uffd2\016\uffd2\020\uffd2\022\uffd2\025\uffd2\027" +
    "\uffd2\030\uffd2\031\uffd2\001\002\000\012\003\113\007\115" +
    "\027\056\031\uffca\001\002\000\004\031\147\001\002\000" +
    "\030\003\uffce\006\uffce\007\uffce\013\uffce\016\uffce\020\uffce" +
    "\022\uffce\025\uffce\027\uffce\030\uffce\031\uffce\001\002\000" +
    "\004\024\151\001\002\000\004\032\152\001\002\000\014" +
    "\003\113\007\115\027\056\030\uffca\031\uffca\001\002\000" +
    "\006\030\155\031\154\001\002\000\030\003\uffd1\006\uffd1" +
    "\007\uffd1\013\uffd1\016\uffd1\020\uffd1\022\uffd1\025\uffd1\027" +
    "\uffd1\030\uffd1\031\uffd1\001\002\000\012\003\113\007\115" +
    "\027\056\031\uffca\001\002\000\004\031\157\001\002\000" +
    "\030\003\uffcd\006\uffcd\007\uffcd\013\uffcd\016\uffcd\020\uffcd" +
    "\022\uffcd\025\uffcd\027\uffcd\030\uffcd\031\uffcd\001\002\000" +
    "\004\024\161\001\002\000\004\032\162\001\002\000\014" +
    "\003\113\007\115\027\056\030\uffca\031\uffca\001\002\000" +
    "\006\030\165\031\164\001\002\000\030\003\uffd3\006\uffd3" +
    "\007\uffd3\013\uffd3\016\uffd3\020\uffd3\022\uffd3\025\uffd3\027" +
    "\uffd3\030\uffd3\031\uffd3\001\002\000\012\003\113\007\115" +
    "\027\056\031\uffca\001\002\000\004\031\167\001\002\000" +
    "\030\003\uffcf\006\uffcf\007\uffcf\013\uffcf\016\uffcf\020\uffcf" +
    "\022\uffcf\025\uffcf\027\uffcf\030\uffcf\031\uffcf\001\002\000" +
    "\016\003\uffe7\013\uffe7\016\uffe7\020\uffe7\024\uffe7\025\uffe7" +
    "\001\002\000\016\003\uffe5\013\uffe5\016\uffe5\020\uffe5\024" +
    "\uffe5\025\uffe5\001\002\000\004\006\uffef\001\002\000\004" +
    "\002\000\001\002\000\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\172\000\006\002\005\003\003\001\001\000\006\002" +
    "\173\003\003\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\004\013\005\016\001\001\000\006" +
    "\006\031\007\027\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\004\026\005\016\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\006\171\007\027\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\010\042\011" +
    "\044\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\010" +
    "\047\011\044\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\010\012\062\013\064\014\057\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\010\012\070\013\064\014\057\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\010\012\066\013\064\014\057\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\015\157\016\100\001\001\000\006" +
    "\015\147\016\100\001\001\000\006\015\137\016\100\001" +
    "\001\000\006\015\077\016\100\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\015\106\016\100\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\014\111\017\113\001\001\000\006\014\111" +
    "\017\136\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\015\130\016\100" +
    "\001\001\000\006\015\126\016\100\001\001\000\006\015" +
    "\124\016\100\001\001\000\006\015\122\016\100\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\014" +
    "\111\017\134\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\014\111\017\142\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\014\111\017\145\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\014\111\017\152\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\014\111\017\155\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\014\111\017\162\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\014\111\017\165\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Pac3Cup$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Pac3Cup$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Pac3Cup$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



	
	
		public static ArrayList parameter;
		public static ArrayList variables;
		
		
		public static Data datVar;
		public static Data datPam;
		public static Data datAttrib;
		
		public static int errorsAnal;
		
		public static int errorsSeman;
		
		public static int id_prod;
		public static String iPar;
		
		
		public static ArrayList results;
		
		public static void printResults(int erroresLexicos){
			
			System.out.println("RESUME:");
			System.out.println("Lexical errors count: " + erroresLexicos);
			System.out.println("Syntactical errors count: " + errorsAnal);
			System.out.println("Semantical errors count " + errorsSeman);
			
			System.out.println("Symbol table content: ");		
			System.out.println(String.format("%10s\t(%10s\t%10s\t%10s\t%10s)","[KEY]","[IDENT]","[SOURCE]","[TYPE]","[SCOPE]"));
	
			Enumeration en = Collections.enumeration(results);
			while(en.hasMoreElements()) {
				Data dat = (Data) en.nextElement(); 
				System.out.println(dat.toString());
				
			} 
			
		}
		
		
		public static void setData(Data dat, ArrayList table){
			table.add(dat);
		}
		
		
		public static void processHashToFinal(ArrayList parameter, ArrayList variables, ArrayList results, String name_class, String iParam, int id_prod){
		
		//parameters:			
			
			
			
			String scope = name_class;
			String iP = "";
			
			if (iParam.equals("")){
				scope+="(NULL)";
				iP = "-";
			}else{
				scope+="("+iParam+")";
				iP = iParam;
			}
			
			
			Enumeration en = Collections.enumeration(parameter);
			
			while(en.hasMoreElements()) { 
				
				Data dat = (Data)en.nextElement(); 
				
				dat.scope = scope;
				dat.id = id_prod;
				
				if (!results.contains(dat)){
					results.add(dat);	
				}else{
					errorsSeman++;
				}
		  	} 
		  	
		//variables:
		
			en = Collections.enumeration(variables);
			
			while(en.hasMoreElements()) { 
				
				Data dat = (Data)en.nextElement(); 
				
				dat.scope = scope;
				dat.id = id_prod;
				
				if (!results.contains(dat)){
					results.add(dat);	
				}else{
					//errorsSeman++;
				}
				
		  	}
		  	
		  	
		  //functions:	
		  Data dat = new Data();
		  dat.ident = name_class;
		  dat.source = "CONSTRUCTOR";
		  dat.type = iP;
		  dat.scope = "-";
		  dat.id = id_prod;
		  
		  if (!results.contains(dat)){
		  	results.add(dat);
		  }else{
		  	errorsSeman++;
		  } 
		  
		
		}
		

		
		public static void main(String[] args) throws Exception {
		
		System.out.println("------------------------------------------");
		System.out.println("JLEX analisis semantico INI				  ");
		System.out.println("------------------------------------------");
	
		if (args.length == 1){
		
			errorsAnal = 0;
			errorsSeman = 0;
			id_prod = 0;
			
			iPar = "";
			
			FileReader fr = new FileReader(new File(args[0]));
			
			results = new ArrayList();
			parameter = new ArrayList();
			variables = new ArrayList();
			
			datVar = new Data();
			datPam = new Data();
			datAttrib = new Data();
			
			Yylex yylex = new Yylex(fr);
			Pac3Cup par = new Pac3Cup(yylex);
			par.parse();
			
			System.out.println("fichero " + args[0] + " procesado! ");
			printResults(yylex.contador);
			
		}else{
			System.out.println("No hay los parametros necesarios");
		}
	
	
		System.out.println("------------------------------------------");
		System.out.println("JLEX analisis semántico FIN				  ");
		System.out.println("------------------------------------------");
	
	
	}	
	

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$Pac3Cup$actions {
  private final Pac3Cup parser;

  /** Constructor */
  CUP$Pac3Cup$actions(Pac3Cup parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$Pac3Cup$do_action(
    int                        CUP$Pac3Cup$act_num,
    java_cup.runtime.lr_parser CUP$Pac3Cup$parser,
    java.util.Stack            CUP$Pac3Cup$stack,
    int                        CUP$Pac3Cup$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Pac3Cup$result;

      /* select the action based on the action number */
      switch (CUP$Pac3Cup$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // sum ::= error 
            {
              Object RESULT =null;
		 Pac3Cup.errorsAnal++;  
              CUP$Pac3Cup$result = parser.getSymbolFactory().newSymbol("sum",12, ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), RESULT);
            }
          return CUP$Pac3Cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // sum ::= TK_OP TK_LITERAL 
            {
              Object RESULT =null;

              CUP$Pac3Cup$result = parser.getSymbolFactory().newSymbol("sum",12, ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.elementAt(CUP$Pac3Cup$top-1)), ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), RESULT);
            }
          return CUP$Pac3Cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // sum ::= TK_NUMBERMAS 
            {
              Object RESULT =null;

              CUP$Pac3Cup$result = parser.getSymbolFactory().newSymbol("sum",12, ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), RESULT);
            }
          return CUP$Pac3Cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // sum ::= TK_OP TK_NUMBER 
            {
              Object RESULT =null;

              CUP$Pac3Cup$result = parser.getSymbolFactory().newSymbol("sum",12, ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.elementAt(CUP$Pac3Cup$top-1)), ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), RESULT);
            }
          return CUP$Pac3Cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // sum ::= TK_OP TK_WORD 
            {
              Object RESULT =null;

              CUP$Pac3Cup$result = parser.getSymbolFactory().newSymbol("sum",12, ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.elementAt(CUP$Pac3Cup$top-1)), ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), RESULT);
            }
          return CUP$Pac3Cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // sumas ::= 
            {
              Object RESULT =null;
		 
              CUP$Pac3Cup$result = parser.getSymbolFactory().newSymbol("sumas",11, ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), RESULT);
            }
          return CUP$Pac3Cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // sumas ::= sum sumas 
            {
              Object RESULT =null;

              CUP$Pac3Cup$result = parser.getSymbolFactory().newSymbol("sumas",11, ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.elementAt(CUP$Pac3Cup$top-1)), ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), RESULT);
            }
          return CUP$Pac3Cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // ifefs ::= 
            {
              Object RESULT =null;
		 
              CUP$Pac3Cup$result = parser.getSymbolFactory().newSymbol("ifefs",13, ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), RESULT);
            }
          return CUP$Pac3Cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // ifefs ::= error 
            {
              Object RESULT =null;
		 Pac3Cup.errorsAnal++;  
              CUP$Pac3Cup$result = parser.getSymbolFactory().newSymbol("ifefs",13, ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), RESULT);
            }
          return CUP$Pac3Cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // ifefs ::= cod ifefs 
            {
              Object RESULT =null;

              CUP$Pac3Cup$result = parser.getSymbolFactory().newSymbol("ifefs",13, ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.elementAt(CUP$Pac3Cup$top-1)), ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), RESULT);
            }
          return CUP$Pac3Cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // cod ::= TK_IF TK_PAROPEN TK_LITERAL sumas TK_PARCLOSE TK_THEN ifefs TK_ELSE ifefs TK_ENDIF 
            {
              Object RESULT =null;
		 
              CUP$Pac3Cup$result = parser.getSymbolFactory().newSymbol("cod",10, ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.elementAt(CUP$Pac3Cup$top-9)), ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), RESULT);
            }
          return CUP$Pac3Cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // cod ::= TK_IF TK_PAROPEN TK_NUMBERMAS sumas TK_PARCLOSE TK_THEN ifefs TK_ELSE ifefs TK_ENDIF 
            {
              Object RESULT =null;
		 
              CUP$Pac3Cup$result = parser.getSymbolFactory().newSymbol("cod",10, ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.elementAt(CUP$Pac3Cup$top-9)), ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), RESULT);
            }
          return CUP$Pac3Cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // cod ::= TK_IF TK_PAROPEN TK_NUMBER sumas TK_PARCLOSE TK_THEN ifefs TK_ELSE ifefs TK_ENDIF 
            {
              Object RESULT =null;
		 
              CUP$Pac3Cup$result = parser.getSymbolFactory().newSymbol("cod",10, ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.elementAt(CUP$Pac3Cup$top-9)), ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), RESULT);
            }
          return CUP$Pac3Cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // cod ::= TK_IF TK_PAROPEN TK_WORD sumas TK_PARCLOSE TK_THEN ifefs TK_ELSE ifefs TK_ENDIF 
            {
              Object RESULT =null;
		 
              CUP$Pac3Cup$result = parser.getSymbolFactory().newSymbol("cod",10, ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.elementAt(CUP$Pac3Cup$top-9)), ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), RESULT);
            }
          return CUP$Pac3Cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // cod ::= TK_IF TK_PAROPEN TK_LITERAL sumas TK_PARCLOSE TK_THEN ifefs TK_ENDIF 
            {
              Object RESULT =null;
		 
              CUP$Pac3Cup$result = parser.getSymbolFactory().newSymbol("cod",10, ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.elementAt(CUP$Pac3Cup$top-7)), ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), RESULT);
            }
          return CUP$Pac3Cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // cod ::= TK_IF TK_PAROPEN TK_NUMBERMAS sumas TK_PARCLOSE TK_THEN ifefs TK_ENDIF 
            {
              Object RESULT =null;
		 
              CUP$Pac3Cup$result = parser.getSymbolFactory().newSymbol("cod",10, ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.elementAt(CUP$Pac3Cup$top-7)), ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), RESULT);
            }
          return CUP$Pac3Cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // cod ::= TK_IF TK_PAROPEN TK_NUMBER sumas TK_PARCLOSE TK_THEN ifefs TK_ENDIF 
            {
              Object RESULT =null;
		 
              CUP$Pac3Cup$result = parser.getSymbolFactory().newSymbol("cod",10, ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.elementAt(CUP$Pac3Cup$top-7)), ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), RESULT);
            }
          return CUP$Pac3Cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // cod ::= TK_IF TK_PAROPEN TK_WORD sumas TK_PARCLOSE TK_THEN ifefs TK_ENDIF 
            {
              Object RESULT =null;
		 
              CUP$Pac3Cup$result = parser.getSymbolFactory().newSymbol("cod",10, ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.elementAt(CUP$Pac3Cup$top-7)), ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), RESULT);
            }
          return CUP$Pac3Cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // cod ::= TK_WORD TK_ASIG TK_LITERAL sumas TK_DOTCOMMA 
            {
              Object RESULT =null;
		 
              CUP$Pac3Cup$result = parser.getSymbolFactory().newSymbol("cod",10, ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.elementAt(CUP$Pac3Cup$top-4)), ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), RESULT);
            }
          return CUP$Pac3Cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // cod ::= TK_WORD TK_ASIG TK_NUMBERMAS sumas TK_DOTCOMMA 
            {
              Object RESULT =null;
		 
              CUP$Pac3Cup$result = parser.getSymbolFactory().newSymbol("cod",10, ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.elementAt(CUP$Pac3Cup$top-4)), ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), RESULT);
            }
          return CUP$Pac3Cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // cod ::= TK_WORD TK_ASIG TK_NUMBER sumas TK_DOTCOMMA 
            {
              Object RESULT =null;
		 
              CUP$Pac3Cup$result = parser.getSymbolFactory().newSymbol("cod",10, ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.elementAt(CUP$Pac3Cup$top-4)), ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), RESULT);
            }
          return CUP$Pac3Cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // cod ::= TK_WORD TK_ASIG TK_WORD sumas TK_DOTCOMMA 
            {
              Object RESULT =null;
		 
              CUP$Pac3Cup$result = parser.getSymbolFactory().newSymbol("cod",10, ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.elementAt(CUP$Pac3Cup$top-4)), ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), RESULT);
            }
          return CUP$Pac3Cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // var ::= error 
            {
              Object RESULT =null;
		 Pac3Cup.errorsAnal++;  
              CUP$Pac3Cup$result = parser.getSymbolFactory().newSymbol("var",9, ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), RESULT);
            }
          return CUP$Pac3Cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // var ::= TK_DOTCOMMA 
            {
              Object RESULT =null;
		  Pac3Cup.datVar.source = "Variable"; 
 		 			      Pac3Cup.setData(Pac3Cup.datVar, Pac3Cup.variables);  
 		 			      String type = Pac3Cup.datVar.type; 
 		 			      Pac3Cup.datVar = new Data(); 
 		 			      Pac3Cup.datVar.type = type;
 		 			      
 		 				
              CUP$Pac3Cup$result = parser.getSymbolFactory().newSymbol("var",9, ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), RESULT);
            }
          return CUP$Pac3Cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // var ::= TK_COMMA 
            {
              Object RESULT =null;
		  Pac3Cup.datVar.source = "Variable"; 
 		 			   Pac3Cup.setData(Pac3Cup.datVar, Pac3Cup.variables);  
 		 			   String type = Pac3Cup.datVar.type; 
 		 			   Pac3Cup.datVar = new Data();
 		 			   Pac3Cup.datVar.type = type;
 		 		   
              CUP$Pac3Cup$result = parser.getSymbolFactory().newSymbol("var",9, ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), RESULT);
            }
          return CUP$Pac3Cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // var ::= TK_WORD 
            {
              Object RESULT =null;
		int wordleft = ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()).left;
		int wordright = ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()).right;
		Object word = (Object)((java_cup.runtime.Symbol) CUP$Pac3Cup$stack.peek()).value;
		 
 		                  String name =  ((pac3.symbol)word).lex; 
 		 				  Pac3Cup.datVar.ident = name; 
 		 			   
              CUP$Pac3Cup$result = parser.getSymbolFactory().newSymbol("var",9, ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), RESULT);
            }
          return CUP$Pac3Cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // var ::= TK_BOOLEAN 
            {
              Object RESULT =null;
		  Pac3Cup.datVar.type = "Boolean"; 
              CUP$Pac3Cup$result = parser.getSymbolFactory().newSymbol("var",9, ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), RESULT);
            }
          return CUP$Pac3Cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // var ::= TK_STRING 
            {
              Object RESULT =null;
		 Pac3Cup.datVar.type = "String"; 
              CUP$Pac3Cup$result = parser.getSymbolFactory().newSymbol("var",9, ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), RESULT);
            }
          return CUP$Pac3Cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // var ::= TK_INTEGER 
            {
              Object RESULT =null;
		  Pac3Cup.datVar.type = "Integer"; 
              CUP$Pac3Cup$result = parser.getSymbolFactory().newSymbol("var",9, ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), RESULT);
            }
          return CUP$Pac3Cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // variables ::= 
            {
              Object RESULT =null;
		  
              CUP$Pac3Cup$result = parser.getSymbolFactory().newSymbol("variables",8, ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), RESULT);
            }
          return CUP$Pac3Cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // variables ::= cod variables 
            {
              Object RESULT =null;

              CUP$Pac3Cup$result = parser.getSymbolFactory().newSymbol("variables",8, ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.elementAt(CUP$Pac3Cup$top-1)), ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), RESULT);
            }
          return CUP$Pac3Cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // variables ::= var variables 
            {
              Object RESULT =null;

              CUP$Pac3Cup$result = parser.getSymbolFactory().newSymbol("variables",8, ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.elementAt(CUP$Pac3Cup$top-1)), ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), RESULT);
            }
          return CUP$Pac3Cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // param ::= error 
            {
              Object RESULT =null;
		 Pac3Cup.errorsAnal++;  
              CUP$Pac3Cup$result = parser.getSymbolFactory().newSymbol("param",7, ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), RESULT);
            }
          return CUP$Pac3Cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // param ::= TK_COMMA 
            {
              Object RESULT =null;
		 
              CUP$Pac3Cup$result = parser.getSymbolFactory().newSymbol("param",7, ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), RESULT);
            }
          return CUP$Pac3Cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // param ::= TK_BOOLEAN TK_WORD 
            {
              Object RESULT =null;
		int wordleft = ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()).left;
		int wordright = ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()).right;
		Object word = (Object)((java_cup.runtime.Symbol) CUP$Pac3Cup$stack.peek()).value;
		 
										
										String name =  ((pac3.symbol)word).lex; 
										Pac3Cup.datPam.ident = name;
										Pac3Cup.datPam.source = "Parameter";
										Pac3Cup.datPam.type = "Boolean";
										Pac3Cup.setData(Pac3Cup.datPam, Pac3Cup.parameter);
										Pac3Cup.datPam = new Data();
										Pac3Cup.iPar += "B";
										
										 
              CUP$Pac3Cup$result = parser.getSymbolFactory().newSymbol("param",7, ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.elementAt(CUP$Pac3Cup$top-1)), ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), RESULT);
            }
          return CUP$Pac3Cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // param ::= TK_STRING TK_WORD 
            {
              Object RESULT =null;
		int wordleft = ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()).left;
		int wordright = ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()).right;
		Object word = (Object)((java_cup.runtime.Symbol) CUP$Pac3Cup$stack.peek()).value;
		
				
										String name =  ((pac3.symbol)word).lex; 
										Pac3Cup.datPam.ident = name;
										Pac3Cup.datPam.source = "Parameter";
										Pac3Cup.datPam.type = "String";
										Pac3Cup.setData(Pac3Cup.datPam, Pac3Cup.parameter);
										Pac3Cup.datPam = new Data();
										Pac3Cup.iPar += "S";	 
											
										
              CUP$Pac3Cup$result = parser.getSymbolFactory().newSymbol("param",7, ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.elementAt(CUP$Pac3Cup$top-1)), ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), RESULT);
            }
          return CUP$Pac3Cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // param ::= TK_INTEGER TK_WORD 
            {
              Object RESULT =null;
		int wordleft = ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()).left;
		int wordright = ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()).right;
		Object word = (Object)((java_cup.runtime.Symbol) CUP$Pac3Cup$stack.peek()).value;
		 
										
										String name =  ((pac3.symbol)word).lex; 
										Pac3Cup.datPam.ident = name;
										Pac3Cup.datPam.source = "Parameter";
										Pac3Cup.datPam.type = "Integer";
										Pac3Cup.setData(Pac3Cup.datPam, Pac3Cup.parameter);
										Pac3Cup.datPam = new Data(); 
										Pac3Cup.iPar += "I";
										
										
              CUP$Pac3Cup$result = parser.getSymbolFactory().newSymbol("param",7, ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.elementAt(CUP$Pac3Cup$top-1)), ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), RESULT);
            }
          return CUP$Pac3Cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // parameters ::= 
            {
              Object RESULT =null;
		 
              CUP$Pac3Cup$result = parser.getSymbolFactory().newSymbol("parameters",6, ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), RESULT);
            }
          return CUP$Pac3Cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // parameters ::= param parameters 
            {
              Object RESULT =null;

              CUP$Pac3Cup$result = parser.getSymbolFactory().newSymbol("parameters",6, ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.elementAt(CUP$Pac3Cup$top-1)), ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), RESULT);
            }
          return CUP$Pac3Cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // function ::= TK_CONSTRUCTOR TK_WORD TK_PAROPEN error 
            {
              Object RESULT =null;
		 Pac3Cup.errorsAnal++;  
              CUP$Pac3Cup$result = parser.getSymbolFactory().newSymbol("function",5, ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.elementAt(CUP$Pac3Cup$top-3)), ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), RESULT);
            }
          return CUP$Pac3Cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // function ::= TK_CONSTRUCTOR TK_WORD error 
            {
              Object RESULT =null;
		 Pac3Cup.errorsAnal++;  
              CUP$Pac3Cup$result = parser.getSymbolFactory().newSymbol("function",5, ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.elementAt(CUP$Pac3Cup$top-2)), ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), RESULT);
            }
          return CUP$Pac3Cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // function ::= TK_CONSTRUCTOR error 
            {
              Object RESULT =null;
		 Pac3Cup.errorsAnal++;  
              CUP$Pac3Cup$result = parser.getSymbolFactory().newSymbol("function",5, ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.elementAt(CUP$Pac3Cup$top-1)), ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), RESULT);
            }
          return CUP$Pac3Cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // function ::= TK_CONSTRUCTOR TK_WORD TK_PAROPEN parameters TK_PARCLOSE TK_BEGIN variables TK_END 
            {
              Object RESULT =null;
		int wordleft = ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.elementAt(CUP$Pac3Cup$top-6)).left;
		int wordright = ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.elementAt(CUP$Pac3Cup$top-6)).right;
		Object word = (Object)((java_cup.runtime.Symbol) CUP$Pac3Cup$stack.elementAt(CUP$Pac3Cup$top-6)).value;
		

String name_class =  ((pac3.symbol)word).lex;
Pac3Cup.processHashToFinal(Pac3Cup.parameter,Pac3Cup.variables,Pac3Cup.results,name_class,Pac3Cup.iPar,Pac3Cup.id_prod);
Pac3Cup.id_prod++;
Pac3Cup.iPar = "";
Pac3Cup.parameter.clear();
Pac3Cup.variables.clear();
Pac3Cup.parameter = new ArrayList();
Pac3Cup.variables = new ArrayList();

              CUP$Pac3Cup$result = parser.getSymbolFactory().newSymbol("function",5, ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.elementAt(CUP$Pac3Cup$top-7)), ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), RESULT);
            }
          return CUP$Pac3Cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // procedures ::= 
            {
              Object RESULT =null;
		 
              CUP$Pac3Cup$result = parser.getSymbolFactory().newSymbol("procedures",4, ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), RESULT);
            }
          return CUP$Pac3Cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // procedures ::= function procedures 
            {
              Object RESULT =null;

              CUP$Pac3Cup$result = parser.getSymbolFactory().newSymbol("procedures",4, ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.elementAt(CUP$Pac3Cup$top-1)), ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), RESULT);
            }
          return CUP$Pac3Cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // attributes ::= error 
            {
              Object RESULT =null;
		 Pac3Cup.errorsAnal++;  
              CUP$Pac3Cup$result = parser.getSymbolFactory().newSymbol("attributes",3, ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), RESULT);
            }
          return CUP$Pac3Cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // attributes ::= TK_DOTCOMMA 
            {
              Object RESULT =null;
		 
					if (!Pac3Cup.results.contains(Pac3Cup.datAttrib)){
						Pac3Cup.results.add(Pac3Cup.datAttrib);
					}else{
						Pac3Cup.errorsSeman++;
					}
					Pac3Cup.datAttrib = new Data();
				
              CUP$Pac3Cup$result = parser.getSymbolFactory().newSymbol("attributes",3, ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), RESULT);
            }
          return CUP$Pac3Cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // attributes ::= TK_COMMA 
            {
              Object RESULT =null;
		
					if (!Pac3Cup.results.contains(Pac3Cup.datAttrib)){
						Pac3Cup.results.add(Pac3Cup.datAttrib);
					}else{
						Pac3Cup.errorsSeman++;
					}
					
					String typeAux = Pac3Cup.datAttrib.type;
					String scopeAux = Pac3Cup.datAttrib.scope;
					Pac3Cup.datAttrib = new Data();
					Pac3Cup.datAttrib.type = typeAux; 
					Pac3Cup.datAttrib.scope = scopeAux;
				
              CUP$Pac3Cup$result = parser.getSymbolFactory().newSymbol("attributes",3, ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), RESULT);
            }
          return CUP$Pac3Cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // attributes ::= TK_WORD 
            {
              Object RESULT =null;
		int wordleft = ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()).left;
		int wordright = ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()).right;
		Object word = (Object)((java_cup.runtime.Symbol) CUP$Pac3Cup$stack.peek()).value;
		
					String name = ((pac3.symbol)word).lex; 
				 	Pac3Cup.datAttrib.ident = name;
				 	Pac3Cup.datAttrib.source = "Attribute";
				
              CUP$Pac3Cup$result = parser.getSymbolFactory().newSymbol("attributes",3, ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), RESULT);
            }
          return CUP$Pac3Cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // attributes ::= TK_STRING 
            {
              Object RESULT =null;
		
				 	Pac3Cup.datAttrib.type = "String";
				
              CUP$Pac3Cup$result = parser.getSymbolFactory().newSymbol("attributes",3, ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), RESULT);
            }
          return CUP$Pac3Cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // attributes ::= TK_INTEGER 
            {
              Object RESULT =null;
		 
				 	Pac3Cup.datAttrib.type = "Integer";
				
              CUP$Pac3Cup$result = parser.getSymbolFactory().newSymbol("attributes",3, ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), RESULT);
            }
          return CUP$Pac3Cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // attributes ::= TK_BOOLEAN 
            {
              Object RESULT =null;
		 
					Pac3Cup.datAttrib.type = "Boolean";
				
              CUP$Pac3Cup$result = parser.getSymbolFactory().newSymbol("attributes",3, ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), RESULT);
            }
          return CUP$Pac3Cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // attributes ::= TK_PRIVATE 
            {
              Object RESULT =null;
		 Pac3Cup.datAttrib.scope = "Private"; 
              CUP$Pac3Cup$result = parser.getSymbolFactory().newSymbol("attributes",3, ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), RESULT);
            }
          return CUP$Pac3Cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // attributes ::= TK_PUBLIC 
            {
              Object RESULT =null;
		 Pac3Cup.datAttrib.scope = "Public"; 
              CUP$Pac3Cup$result = parser.getSymbolFactory().newSymbol("attributes",3, ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), RESULT);
            }
          return CUP$Pac3Cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // global ::= 
            {
              Object RESULT =null;
		 
              CUP$Pac3Cup$result = parser.getSymbolFactory().newSymbol("global",2, ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), RESULT);
            }
          return CUP$Pac3Cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // global ::= attributes global 
            {
              Object RESULT =null;

              CUP$Pac3Cup$result = parser.getSymbolFactory().newSymbol("global",2, ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.elementAt(CUP$Pac3Cup$top-1)), ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), RESULT);
            }
          return CUP$Pac3Cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // program ::= TK_CLASS TK_WORD error 
            {
              Object RESULT =null;
		 Pac3Cup.errorsAnal++;  
              CUP$Pac3Cup$result = parser.getSymbolFactory().newSymbol("program",1, ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.elementAt(CUP$Pac3Cup$top-2)), ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), RESULT);
            }
          return CUP$Pac3Cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // program ::= TK_CLASS error 
            {
              Object RESULT =null;
		 Pac3Cup.errorsAnal++;  
              CUP$Pac3Cup$result = parser.getSymbolFactory().newSymbol("program",1, ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.elementAt(CUP$Pac3Cup$top-1)), ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), RESULT);
            }
          return CUP$Pac3Cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // program ::= error 
            {
              Object RESULT =null;
		 Pac3Cup.errorsAnal++;  
              CUP$Pac3Cup$result = parser.getSymbolFactory().newSymbol("program",1, ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), RESULT);
            }
          return CUP$Pac3Cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // program ::= TK_CLASS TK_WORD TK_BEGIN global procedures TK_END 
            {
              Object RESULT =null;
		int wordleft = ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.elementAt(CUP$Pac3Cup$top-4)).left;
		int wordright = ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.elementAt(CUP$Pac3Cup$top-4)).right;
		Object word = (Object)((java_cup.runtime.Symbol) CUP$Pac3Cup$stack.elementAt(CUP$Pac3Cup$top-4)).value;

              CUP$Pac3Cup$result = parser.getSymbolFactory().newSymbol("program",1, ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.elementAt(CUP$Pac3Cup$top-5)), ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), RESULT);
            }
          return CUP$Pac3Cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // file ::= 
            {
              Object RESULT =null;
		 
              CUP$Pac3Cup$result = parser.getSymbolFactory().newSymbol("file",0, ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), RESULT);
            }
          return CUP$Pac3Cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= file EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.elementAt(CUP$Pac3Cup$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.elementAt(CUP$Pac3Cup$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Pac3Cup$stack.elementAt(CUP$Pac3Cup$top-1)).value;
		RESULT = start_val;
              CUP$Pac3Cup$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.elementAt(CUP$Pac3Cup$top-1)), ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Pac3Cup$parser.done_parsing();
          return CUP$Pac3Cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // file ::= program file 
            {
              Object RESULT =null;

              CUP$Pac3Cup$result = parser.getSymbolFactory().newSymbol("file",0, ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.elementAt(CUP$Pac3Cup$top-1)), ((java_cup.runtime.Symbol)CUP$Pac3Cup$stack.peek()), RESULT);
            }
          return CUP$Pac3Cup$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

