
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Jan 24 14:45:19 CET 2014
//----------------------------------------------------

package pac2;

/** CUP generated interface containing symbol constants. */
public interface Pac2Sym {
  /* terminals */
  public static final int TK_PARCLOSE = 18;
  public static final int TK_PUBLIC = 11;
  public static final int TK_ASIG = 15;
  public static final int TK_STRING = 12;
  public static final int TK_NUMBERMAS = 7;
  public static final int TK_LITERAL = 8;
  public static final int TK_CLASS = 2;
  public static final int TK_NUMBER = 6;
  public static final int TK_ENDIF = 23;
  public static final int TK_ELSE = 22;
  public static final int TK_WORD = 5;
  public static final int TK_BOOLEAN = 14;
  public static final int TK_THEN = 24;
  public static final int TK_PAROPEN = 17;
  public static final int TK_CONSTRUCTOR = 13;
  public static final int EOF = 0;
  public static final int TK_BEGIN = 3;
  public static final int TK_COMENTARIO = 9;
  public static final int TK_COMMA = 19;
  public static final int TK_INTEGER = 10;
  public static final int error = 1;
  public static final int TK_OP = 20;
  public static final int TK_DOTCOMMA = 16;
  public static final int TK_END = 4;
  public static final int TK_IF = 21;
}

