/* The following code was generated by JFlex 1.4.3 on 24/01/14 14:45 */

package pac2;

import java_cup.runtime.Symbol;
import java.io.*;

class symbol{
	public String lex;
	
	public symbol (String str) {
		lex = new String(str);
	}
	
}


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 24/01/14 14:45 from the specification file
 * <tt>C:/workspaces/worksEclipse/LEXCup-2/res/pac2.lex</tt>
 */
class Yylex implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0, 32,  5,  0, 32,  5,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
    32, 29,  6,  0,  0,  0, 29,  0, 26, 27, 29,  3, 28,  3,  0,  4, 
     2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  0, 25, 30, 24, 31,  0, 
     0,  9, 11,  7, 16, 12, 22, 13, 23, 14,  1,  1,  8,  1, 15, 21, 
    19,  1, 18, 10, 17, 20,  1,  1,  1,  1,  1,  0,  0,  0, 29,  0, 
     0,  9, 11,  7, 16, 12, 22, 13, 23, 14,  1,  1,  8,  1, 15, 21, 
    19,  1, 18, 10, 17, 20,  1,  1,  1,  1,  1,  0, 29,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\2\4\1\5\1\1\10\2"+
    "\1\6\1\7\1\10\1\11\1\12\2\4\1\2\1\13"+
    "\1\14\1\0\1\15\10\2\1\16\12\2\1\17\12\2"+
    "\1\20\2\2\1\21\1\22\1\2\1\23\2\2\1\24"+
    "\1\2\1\25\3\2\1\26\2\2\1\27\1\2\1\30"+
    "\1\31\3\2\1\32";

  private static int [] zzUnpackAction() {
    int [] result = new int[84];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\41\0\102\0\143\0\204\0\245\0\41\0\306"+
    "\0\347\0\u0108\0\u0129\0\u014a\0\u016b\0\u018c\0\u01ad\0\u01ce"+
    "\0\41\0\41\0\41\0\41\0\41\0\41\0\u01ef\0\u0210"+
    "\0\41\0\u0231\0\306\0\306\0\u0252\0\u0273\0\u0294\0\u02b5"+
    "\0\u02d6\0\u02f7\0\u0318\0\u0339\0\102\0\u035a\0\u037b\0\u039c"+
    "\0\u03bd\0\u03de\0\u03ff\0\u0420\0\u0441\0\u0462\0\u0483\0\u04a4"+
    "\0\u04c5\0\u04e6\0\u0507\0\u0528\0\u0549\0\u056a\0\u058b\0\u05ac"+
    "\0\u05cd\0\u05ee\0\102\0\u060f\0\u0630\0\102\0\102\0\u0651"+
    "\0\102\0\u0672\0\u0693\0\102\0\u06b4\0\102\0\u06d5\0\u06f6"+
    "\0\u0717\0\102\0\u0738\0\u0759\0\102\0\u077a\0\102\0\102"+
    "\0\u079b\0\u07bc\0\u07dd\0\102";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[84];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\2\3\1\12\1\13\1\14\1\3\1\15\2\3\1\16"+
    "\1\3\1\17\2\3\1\20\1\3\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\1\27\1\26\1\7\42\0\1\3"+
    "\1\30\4\0\21\3\13\0\1\4\40\0\1\31\42\0"+
    "\1\32\34\0\5\33\1\0\1\34\32\33\1\0\1\3"+
    "\1\30\4\0\1\3\1\35\14\3\1\36\2\3\12\0"+
    "\1\3\1\30\4\0\12\3\1\37\6\3\12\0\1\3"+
    "\1\30\4\0\5\3\1\40\10\3\1\41\2\3\12\0"+
    "\1\3\1\30\4\0\1\3\1\42\6\3\1\43\10\3"+
    "\12\0\1\3\1\30\4\0\10\3\1\44\6\3\1\45"+
    "\1\3\12\0\1\3\1\30\4\0\13\3\1\46\4\3"+
    "\1\47\12\0\1\3\1\30\4\0\15\3\1\50\3\3"+
    "\12\0\1\3\1\30\4\0\2\3\1\51\16\3\50\0"+
    "\1\26\3\0\1\30\36\0\5\32\1\0\33\32\1\0"+
    "\1\3\1\30\4\0\2\3\1\52\16\3\12\0\1\3"+
    "\1\30\4\0\10\3\1\53\10\3\12\0\1\3\1\30"+
    "\4\0\13\3\1\54\5\3\12\0\1\3\1\30\4\0"+
    "\6\3\1\55\12\3\12\0\1\3\1\30\4\0\16\3"+
    "\1\56\2\3\12\0\1\3\1\30\4\0\3\3\1\57"+
    "\15\3\12\0\1\3\1\30\4\0\11\3\1\60\7\3"+
    "\12\0\1\3\1\30\4\0\12\3\1\61\6\3\12\0"+
    "\1\3\1\30\4\0\15\3\1\62\3\3\12\0\1\3"+
    "\1\30\4\0\5\3\1\63\13\3\12\0\1\3\1\30"+
    "\4\0\4\3\1\64\14\3\12\0\1\3\1\30\4\0"+
    "\1\3\1\65\17\3\12\0\1\3\1\30\4\0\3\3"+
    "\1\66\15\3\12\0\1\3\1\30\4\0\3\3\1\67"+
    "\15\3\12\0\1\3\1\30\4\0\7\3\1\70\11\3"+
    "\12\0\1\3\1\30\4\0\7\3\1\71\11\3\12\0"+
    "\1\3\1\30\4\0\1\3\1\72\17\3\12\0\1\3"+
    "\1\30\4\0\5\3\1\73\13\3\12\0\1\3\1\30"+
    "\4\0\7\3\1\74\11\3\12\0\1\3\1\30\4\0"+
    "\5\3\1\75\13\3\12\0\1\3\1\30\4\0\5\3"+
    "\1\76\13\3\12\0\1\3\1\30\4\0\10\3\1\77"+
    "\10\3\12\0\1\3\1\30\4\0\1\3\1\100\17\3"+
    "\12\0\1\3\1\30\4\0\3\3\1\62\15\3\12\0"+
    "\1\3\1\30\4\0\3\3\1\101\15\3\12\0\1\3"+
    "\1\30\4\0\12\3\1\102\6\3\12\0\1\3\1\30"+
    "\4\0\10\3\1\103\10\3\12\0\1\3\1\30\4\0"+
    "\10\3\1\104\10\3\12\0\1\3\1\30\4\0\5\3"+
    "\1\105\13\3\12\0\1\3\1\30\4\0\17\3\1\106"+
    "\1\3\12\0\1\3\1\30\4\0\6\3\1\107\12\3"+
    "\12\0\1\3\1\30\4\0\7\3\1\110\11\3\12\0"+
    "\1\3\1\30\4\0\13\3\1\111\5\3\12\0\1\3"+
    "\1\30\4\0\6\3\1\112\12\3\12\0\1\3\1\30"+
    "\4\0\2\3\1\113\16\3\12\0\1\3\1\30\4\0"+
    "\5\3\1\114\13\3\12\0\1\3\1\30\4\0\1\115"+
    "\20\3\12\0\1\3\1\30\4\0\15\3\1\116\3\3"+
    "\12\0\1\3\1\30\4\0\10\3\1\117\10\3\12\0"+
    "\1\3\1\30\4\0\13\3\1\120\5\3\12\0\1\3"+
    "\1\30\4\0\1\121\20\3\12\0\1\3\1\30\4\0"+
    "\12\3\1\122\6\3\12\0\1\3\1\30\4\0\16\3"+
    "\1\123\2\3\12\0\1\3\1\30\4\0\13\3\1\124"+
    "\5\3\11\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2046];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\4\1\1\11\11\1\6\11\2\1\1\11"+
    "\1\1\1\0\71\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[84];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
public int contador;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Yylex(java.io.Reader in) {
  	contador = 0;
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Yylex(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 23: 
          { return new Symbol(Pac2Sym.TK_PUBLIC);
          }
        case 27: break;
        case 3: 
          { return new Symbol(Pac2Sym.TK_NUMBER, new symbol(yytext()));
          }
        case 28: break;
        case 10: 
          { return new Symbol(Pac2Sym.TK_COMMA);
          }
        case 29: break;
        case 24: 
          { return new Symbol(Pac2Sym.TK_BOOLEAN);
          }
        case 30: break;
        case 13: 
          { return new Symbol(Pac2Sym.TK_LITERAL);
          }
        case 31: break;
        case 7: 
          { return new Symbol(Pac2Sym.TK_DOTCOMMA);
          }
        case 32: break;
        case 19: 
          { return new Symbol(Pac2Sym.TK_CLASS);
          }
        case 33: break;
        case 18: 
          { return new Symbol(Pac2Sym.TK_THEN);
          }
        case 34: break;
        case 20: 
          { return new Symbol(Pac2Sym.TK_BEGIN);
          }
        case 35: break;
        case 6: 
          { return new Symbol(Pac2Sym.TK_ASIG);
          }
        case 36: break;
        case 4: 
          { return new Symbol(Pac2Sym.TK_OP);
          }
        case 37: break;
        case 26: 
          { return new Symbol(Pac2Sym.TK_CONSTRUCTOR);
          }
        case 38: break;
        case 8: 
          { return new Symbol(Pac2Sym.TK_PAROPEN);
          }
        case 39: break;
        case 21: 
          { return new Symbol(Pac2Sym.TK_ENDIF);
          }
        case 40: break;
        case 11: 
          { return new Symbol(Pac2Sym.TK_NUMBERMAS, new symbol(yytext()));
          }
        case 41: break;
        case 12: 
          { return new Symbol(Pac2Sym.TK_COMENTARIO);
          }
        case 42: break;
        case 2: 
          { return new Symbol(Pac2Sym.TK_WORD, new symbol(yytext()));
          }
        case 43: break;
        case 15: 
          { return new Symbol(Pac2Sym.TK_END);
          }
        case 44: break;
        case 22: 
          { return new Symbol(Pac2Sym.TK_STRING);
          }
        case 45: break;
        case 25: 
          { return new Symbol(Pac2Sym.TK_INTEGER);
          }
        case 46: break;
        case 9: 
          { return new Symbol(Pac2Sym.TK_PARCLOSE);
          }
        case 47: break;
        case 16: 
          { return new Symbol(Pac2Sym.TK_ELSE);
          }
        case 48: break;
        case 1: 
          { contador++;
          }
        case 49: break;
        case 14: 
          { return new Symbol(Pac2Sym.TK_IF);
          }
        case 50: break;
        case 5: 
          { /* ignore white space. */
          }
        case 51: break;
        case 17: 
          { 
          }
        case 52: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              {   return new java_cup.runtime.Symbol(Pac2Sym.EOF);
 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
